name: Hello World with WorkFlow 
on: 
  workflow_dispatch: 
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Saludo
        run: echo "Bienvenidos a todos"
      - name: fechaSistema
        run: |
          echo "Bienvenidos a mi primer desafio que fue realizado por Laura Berenice Tapia Cid a las: $(date)"
